# Generated by Django 5.0.6 on 2024-06-30 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitor",
            old_name="created_at",
            new_name="timestamp",
        ),
    ]
