# Generated by Django 5.0.6 on 2024-07-01 20:04

import imagekit.models.fields
import taggit.managers
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_created_at_visitor_timestamp"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(upload_to="images/"),
        ),
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
